apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-reviews-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-reviews-app
  template:
    metadata:
      labels:
        app: movie-reviews-app
    spec:
      containers:
        - name: movie-reviews-container
          image: benjlb/movie-reviews:v4
          ports:
            - containerPort: 8086
          resources:
            limits:
              cpu: "1"  # Limit to 1 CPU
              memory: "512Mi"  # Limit to 512 MB RAM
            requests:
              cpu: "0.5"  # Request 0.5 CPUs
              memory: "256Mi"  # Request 256 MB RAM
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: key
