apiVersion: apps/v1
kind: Deployment
metadata:
  name: omdbapi #restful-ms-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omdbapi #restful-ms-app
  template:
    metadata:
      labels:
        app: omdbapi #restful-ms-app
    spec:
      containers:
      - name: omdbapi-container #restful-ms-app-container
        image: eleanorburke/omdbapi:1.0.0
        imagePullPolicy: Always
        env:
        # Define the environment variable
        - name: DATA_MICROSERVICE
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: my-configmap
              # Specify the key associated with the value
              key: DATA_MICROSERVICE
        ports:
        - containerPort: 1234
