apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies
  namespace: omd-movies 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movies 
  template:
    metadata:
      labels:
        app: movies 
    spec:
      containers:
      - name: movies-container
        image: sokp/omdbapi:v1 #sean's image here
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
