apiVersion: v1
kind: Service
metadata:
  name: movies-service
  namespace: omd-movies
spec:
  type: ClusterIP
  selector:
    app: movies
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000