apiVersion: v1
kind: Service
metadata:
  name: omdbapi-service
spec:
  type: NodePort
  selector:
    app: omdbapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 3000